Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.11.11/x64/lib/python3.11/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/opt/hostedtoolcache/Python/3.11.11/x64/lib/python3.11/site-packages/nbclient/client.py", line 1319, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.11/x64/lib/python3.11/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.11/x64/lib/python3.11/asyncio/base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.11/x64/lib/python3.11/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/opt/hostedtoolcache/Python/3.11.11/x64/lib/python3.11/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/hostedtoolcache/Python/3.11.11/x64/lib/python3.11/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import tabulate

data = [['P (atm)', 'V (L/mol)',   'Z']]

for p in [56, 111.3, 222.6, 445.2, 1113, 2226]:
    sol = root(vdw_zero, 0.5, args=(p,))
    
    V = sol.x[0]
    Z = p * V / R / T
    data += [[p, V, Z]]
    
print(tabulate.tabulate(data, headers='firstrow'))


------------------


[31m---------------------------------------------------------------------------[39m
[31mNameError[39m                                 Traceback (most recent call last)
[36mCell[39m[36m [39m[32mIn[2][39m[32m, line 6[39m
[32m      3[39m data = [[[33m'[39m[33mP (atm)[39m[33m'[39m, [33m'[39m[33mV (L/mol)[39m[33m'[39m,   [33m'[39m[33mZ[39m[33m'[39m]]
[32m      5[39m [38;5;28;01mfor[39;00m p [38;5;129;01min[39;00m [[32m56[39m, [32m111.3[39m, [32m222.6[39m, [32m445.2[39m, [32m1113[39m, [32m2226[39m]:
[32m----> [39m[32m6[39m     sol = [43mroot[49m(vdw_zero, [32m0.5[39m, args=(p,))
[32m      8[39m     V = sol.x[[32m0[39m]
[32m      9[39m     Z = p * V / R / T

[31mNameError[39m: name 'root' is not defined

